SachOnline/Models/SACH.cs
namespace SachOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("SACH")]
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            CHITIETDONTHANGs = new HashSet<CHITIETDONTHANG>();
            VIETSACHes = new HashSet<VIETSACH>();
        }

        [Key]
        public int Masach { get; set; }

        [Required]
        [StringLength(100)]
        public string Tensach { get; set; }

        public decimal? Giaban { get; set; }

        public string Mota { get; set; }

        
        public string Anhbia { get; set; }

        public DateTime? Ngaycapnhat { get; set; }

        public int? Soluongton { get; set; }

        public int? MaCD { get; set; }

        public int? MaNXB { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONTHANG> CHITIETDONTHANGs { get; set; }

        public virtual CHUDE CHUDE { get; set; }

        public virtual NHAXUATBAN NHAXUATBAN { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIETSACH> VIETSACHes { get; set; }
    }
}

SachOnline/Areas/Admin/Controllers/SachController.cs
using SachOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PagedList;
using System.Web.Mvc;
using System.IO;
using System.Drawing;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.Migrations;

namespace SachOnline.Areas.Admin.Controllers
{
    public class SachController : Controller
    {
        // GET: Admin/Sach
        Model1 db = new Model1();
        public ActionResult Index(int ? page)
        {
            var lstSaches = db.SACHes.OrderBy(s => s.Masach);
            int pageNum = (page ?? 1);
            int pageSize = 7;
            return View(db.SACHes.ToList().OrderBy(n=>n.Masach).ToPagedList(pageNum,pageSize));
        }
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.MaCD = new SelectList(db.CHUDEs.ToList().OrderBy(n => n.TenChuDe), "MaCD", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NHAXUATBANs.ToList().OrderBy(n => n.MaNXB), "MaNXB", "TenNXB");
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(SACH model, FormCollection f, HttpPostedFileBase fFileUpload)
        {
            if (ModelState.IsValid)
            {
                if (fFileUpload != null)
                {
                    Image img = Image.FromStream(fFileUpload.InputStream, true, true);
                    model.Anhbia = Utility.ConvertImageToBase64(img);
                }
                db.SACHes.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Detail(int id)
        {
            var hotel = db.SACHes.SingleOrDefault(n => n.Masach == id);
            if (hotel == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(hotel);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var sach = db.SACHes.SingleOrDefault(n => n.Masach == id);
            ViewBag.MaCD = new SelectList(db.CHUDEs.ToList().OrderBy(n => n.TenChuDe), "MaCD", "TenChuDe",sach.MaCD);
            ViewBag.MaNXB = new SelectList(db.NHAXUATBANs.ToList().OrderBy(n => n.MaNXB), "MaNXB", "TenNXB",sach.MaNXB);
            return View(sach);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(SACH model, HttpPostedFileBase fFileUpload)
        {
            if (ModelState.IsValid)
            {
                if (fFileUpload != null)
                {
                    Image img = Image.FromStream(fFileUpload.InputStream, true, true);
                    model.Anhbia = Utility.ConvertImageToBase64(img);
                }
                db.SACHes.AddOrUpdate(model);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            var sach = db.SACHes.FirstOrDefault(s => s.Masach == id);
            if (sach == null)
            {
                TempData["Message"] = "Sách không tồn tại";
                return RedirectToAction("Index");
            }
            var ctdh = db.CHITIETDONTHANGs.Where(ct => ct.Masach == id).ToList();
            if (ctdh.Count() > 0)
            {
                TempData["Message"] = "Sách tồn tại đơn đặt hàng không thể xóa";
                return RedirectToAction("Index");
            }
            var vietSach = db.VIETSACHes.Where(tg => tg.MaSach == id);
            if (vietSach.Count() > 0)
            {
                db.VIETSACHes.RemoveRange(vietSach);
                db.SaveChanges();
            }
            db.SACHes.Remove(sach);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SachOnline/Areas/Admin/Views/Sach/Create.cshtml
@model SachOnline.Models.SACH

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Sach", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SACH</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Tensach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tensach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tensach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anhbia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="fFileUpload" accept="image/*" />
                @Html.ValidationMessageFor(model => model.Anhbia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Mota, new { @class = "form-control", id = "mota" })
                @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
                <script>
                    CKEDITOR.replace('mota');
                </script>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Giaban, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Giaban, new { @class = "form-control", type = "number", step = "1" })
                @Html.ValidationMessageFor(model => model.Giaban, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Soluongton, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Soluongton, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Soluongton, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Ngaycapnhat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ngaycapnhat, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @Value = DateTime.Now.ToString("yyyy-MM-dd") } })
                @Html.ValidationMessageFor(model => model.Ngaycapnhat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaCD, "MaCD", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaCD", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaCD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNXB, "MaNXB", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNXB", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNXB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SachOnline/Areas/Admin/Views/Sach/Detail.cshtml
@model SachOnline.Models.SACH
@helper Truncate(string s, int length)
{
    if (s.Length < length)
    {
        @s
    }
    else
    {
        @s.Substring(0, length)<text>...</text>
    }
}
@{
    ViewBag.Title = "Detail";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<style type="text/css">
    img {
        width: 200px;
        margin-bottom: 20px;
    }
</style>
<h2 style="text-align:center">SACH DETAIL</h2>


<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Chủ đề:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CHUDE.TenChuDe)
        </dd>

        <dt>
            Nhà xuất bản:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NHAXUATBAN.TenNXB)
        </dd>
        <dt>
            Tên sách:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tensach)
        </dd>
        <dt>
            Ảnh bìa:
        </dt>
        <dd>
            <img src="@Model.Anhbia" alt=" @Model.Tensach">
        </dd>
        <dt>
            Mô tả:
        </dt>
        <dd>
            @Html.Raw(HttpUtility.HtmlDecode(Truncate((Model.Mota) ?? "", 70).ToString()))
        </dd>
        <dt>
            Số lượng tồn:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Soluongton)
        </dd>
        <dt>
            Giá bán:
        </dt>
        <dd>
            @string.Format("{0:#,##0}", Model.Giaban) VNĐ
        </dd>
        <dt>
            Ngày cập nhật:
        </dt>
        <dd>
            @Html.FormatValue(@Model.Ngaycapnhat, "{0:dd/MM/yyyy}")
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Masach }) |
    @Html.ActionLink("Back", "Index")
</p>

SachOnline/Areas/Admin/Views/Sach/Edit.cshtml
@model SachOnline.Models.SACH

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<!-- Include CKEditor script -->
<script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>

<h2>EDIT SACH</h2>
@using (Html.BeginForm("Edit", "Sach", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Mã sách:</label>
            <div class="col-md-10">
                <input type="text" size="70" name="MASACH" value="@Model.Masach" readonly />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Tên sách:</label>
            <div class="col-md-10">
                <input type="text" size="70" name="TENSACH" value="@Model.Tensach" required />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Mô tả:</label>
            <div class="col-md-10">
                <textarea name="MOTA" id="mota">@Model.Mota</textarea>
                <script>
                    // CKEditor initialization
                    CKEDITOR.replace('mota');
                </script>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Ảnh bìa:</label>
            <div class="col-md-10">
                <input type="file" name="fFileUpload" />
                <img src="@Model.Anhbia" width="120">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Ngày cập nhật:</label>
            <div class="col-md-10">
                <input type="datetime" name="NGAYCAPNHAT" required value="@Convert.ToDateTime(Model.Ngaycapnhat)" readonly />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Số lượng tồn:</label>
            <div class="col-md-10">
                <input type="number" min="1" required name="SOLUONGTON" value="@Model.Soluongton" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Giá bán:</label>
            <div class="col-md-10">
                <input type="number" min="1" required name="GIABAN" value="@Model.Giaban" />
            </div>
        </div>
                <div class="form-group">
            @Html.LabelFor(model => model.MaCD, "MaCD", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaCD", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaCD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNXB, "MaNXB", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNXB", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNXB, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back", "Index")
</div>

SachOnline/Areas/Admin/Views/Sach/Index.cshtml
@*@model IEnumerable<SachOnline.Models.SACH>*@
@using SachOnline.Models
@using PagedList.Mvc;
@helper Truncate(string s, int length)
{
    if (s.Length < length)
    {
        @s
    }
    else
    {
        @s.Substring(0, length)<text>...</text>
    }
}

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Tên chủ đề
        </th>
        <th>
            Giaban
        </th>
        <th>
            Mota
        </th>
        <th>
            Anhbia
        </th>
        <th>
            Ngaycapnhat
        </th>
        <th>
            Soluongton
        </th>
        <th>
            MaCD
        </th>
        <th>
            MaNXB
        </th>
        <th style="width:250px"></th>
    </tr>

    @foreach (SACH item in Model)
    {
        <tr>
            <td>
                @Truncate(item.Tensach, 50)
                @*@Html.DisplayFor(modelItem => item.Tensach)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Giaban)
            </td>
            <td>
                @Html.Raw(Truncate(item.Mota, 70))
            </td>
            <td>
                <img src="@item.Anhbia" style="width:50px" />
            </td>
            <td>
                @Html.FormatValue(item.Ngaycapnhat, "{0:dd/MM/yyyy}")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Soluongton)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaCD)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaNXB)
            </td>
            <td>
                <a href="@Url.Action("Edit", new {id=item.Masach})" class="btn btn-primary">Edit</a>
                <a href="@Url.Action("Detail", new {id=item.Masach})" class="btn btn-light">Detail</a>
                <a href="@Url.Action("Delete", new {id=item.Masach})" class="btn btn-danger">Delete</a>
            </td>
        </tr>
    }

</table>
@if (ViewBag.Message != null)
{
    <script type="text/javascript">

            window.onload = function () {
                alert("@ViewBag.Message");
            };
    </script>

}
<nav aria-label="Page navigation example" class="text-center">
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(
        (PagedList.IPagedList)Model, page => Url.Action("Index", new { page = page })
    )
</nav>