SachOnline/Controllers/SachOnlineController.cs
using SachOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace SachOnline.Controllers
{
    public class SachOnlineController : Controller
    {
        Model1 db = new Model1();
        // GET: SachOnline
        public ActionResult Index(int?page)
        {
            var lstSach = db.SACHes.OrderBy(s=>s.Masach);
            int pageNumber = (page) ?? 1;
            int pageSize = 3;
            ViewBag.TieuDe = "SÁCH MỚI";
            return View(lstSach.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult ChuDePartial()
        {
            var lstCHUDE = db.CHUDEs;
            return PartialView(lstCHUDE);
        }
        public ActionResult NavPartial()
        {
            var dropChuDe =new object[] { db.CHUDEs,db.NHAXUATBANs};
            return PartialView(dropChuDe);
        }
        public ActionResult SachBanPartial()
        {
            var Sach = db.SACHes;
            return PartialView(Sach);
        }
        public ActionResult NXBPartial()
        {
            var NXB = db.NHAXUATBANs;
            return PartialView(NXB);
        }
        public ActionResult SachTheoChuDe(int MaCD)
        {
            var lstSach = db.SACHes.Where(s => s.MaCD == MaCD);
            return View(lstSach);
        }
        public ActionResult ChiTietSach(int MaSach)
        {
            var sach=db.SACHes.FirstOrDefault( s=>s.Masach ==MaSach);
            return View(sach);
        }
    }
}

SachOnline/Views/SachOnline/ChiTietSach.cshtml
@model SachOnline.Models.SACH
@{
    ViewBag.Title = "ChiTietSach";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>ChiTietSach</h2>
<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container mt-5">
        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-md-6 mb-4">
                <img src=@Model.Anhbia class="img-fluid" alt="" />
            </div>
            <!--Grid column-->
            <!--Grid column-->
            <div class="col-md-6 mb-4">
                <!--Content-->
                <div class="p-4">
                    <div class="mb-3">
                        <a href="">
                            <span class="badge bg-dark me-1">Category 2</span>
                        </a>
                        <a href="">
                            <span class="badge bg-info me-1">New</span>
                        </a>
                        <a href="">
                            <span class="badge bg-danger me-1">Bestseller</span>
                        </a>
                    </div>

                    <p class="lead">
                        <span class="me-1">
                            <del>1.000.000đ</del>
                        </span>
                        <span>@Model.Giaban đ</span>
                    </p>

                    <strong><p style="font-size: 20px;">Description</p></strong>

                    <p>@Model.Mota</p>

                    <form class="d-flex justify-content-left">
                        <!-- Default input -->
                        <div class="form-outline me-1" style="width: 100px;">
                            <input type="number" value="1" class="form-control" />
                        </div>
                        <button class="btn btn-primary ms-1" type="submit">
                            Add to cart
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart2" viewBox="0 0 16 16">
                                <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z" />
                            </svg>
                        </button>
                    </form>
                </div>
                <!--Content-->
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->
        <hr />
    </div>
</main>
<!--Main layout-->

SachOnline/Views/SachOnline/Index.cshtml
@using PagedList.Mvc
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<h2 class="text-center">SÁCH MỚI</h2>
<hr>
<div class="row text-center container body-content">
    @foreach (var item in Model)
    {
        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-6">
            <a style="text-decoration:none" href=@Url.Action("ChiTietSach", "SachOnline", new {MaSach=item.Masach})>
                <div class="thumbnail">
                    <img src=@item.Anhbia class="img-thumbnail rounded-5" alt="...">
                    <div class="caption">
                        <h4>@item.Tensach</h4>
                        <p>@item.Mota</p>
                    </div>
                </div>
            </a>
            <p>
                <a href="@Url.Action("AddToCart", "Cart", new {Masach = item.Masach})" class="btn btn-primary" role="button">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart2" viewBox="0 0 16 16">
                        <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z" />
                    </svg> Add to Cart
                </a>
            </p>
        </div>
    }
</div>
<nav aria-label="Page navigation example" class="text-center">
    @Html.PagedListPager(
        (PagedList.IPagedList)Model,page => Url.Action("Index", new { page = page })
    )
</nav>
@*Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount*@
@*This is to display the page number*@

SachOnline/Views/SachOnline/SachTheoChuDe.cshtml
@{
    ViewBag.Title = "SachTheoChuDe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SachTheoChuDe</h2>
<div class="row text-center container body-content">
    @foreach (var item in Model)
    {
        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-6">
            <div class="thumbnail">
                <img src=@item.Anhbia class="img-thumbnail rounded-5" alt="...">
                <div class="caption">
                    <a href=@Url.Action("ChiTietSach", "SachOnline", new {id=item.Masach})>@item.Tensach </a>
                    <p>@item.Mota</p>
                    <p>
                        <a href="#" class="btn btn-primary" role="button">
                            <span class="glyphiconglyphicon-shopping-cart" aria-hidden="true"></span> Add to Cart
                        </a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>